---
title: "Measuring the Impact of NCAA Football Head Coach Changes"
author: "By: Jack Miller, Alex Jackson, and Bryce Grove" 
output: "html_document"
---

# Introduction

Our project examines NCAA Division 1 football teams who made head coach changes 
in the last ten years. 




```{r load packages}
library(tidyverse)
library(readr)
library(dplyr)
library(stringr)
library(data.table)
```

```{r load data}
csv21 <- read_csv("Data/cfb21.csv")
coach13 <- read_csv("Data/2013_Coaches.csv")
coach14 <- read_csv("Data/2014_Coaches.csv")
coach15 <- read_csv("Data/2015_Coaches.csv")
coach16 <- read_csv("Data/2016_Coaches.csv") %>% 
  select(-Year) %>% 
  mutate(Year = 2016)
coach17 <- read_csv("Data/2017_Coaches.csv")
coach18 <- read_csv("Data/2018_Coaches.csv")
coach19 <- read_csv("Data/2019_Coaches.csv")
coach20 <- read_csv("Data/2020_Coaches.csv")
coach21 <- read_csv("Data/2021_Coaches.csv")
cfb13 <- read_csv("Data/cfb13.csv") %>% 
  mutate(Year = 2013) %>% 
  mutate(Team = case_when(
    Team == "Miami (FL) (ACC)" ~ "Miami_FL (ACC)",
    Team == "Miami (OH) (MAC)" ~ "Miami_OH (MAC)",
    TRUE ~ Team
  )) %>% separate(col = "Team", into = "Team", sep = " [(]")
cfb14 <- read_csv("Data/cfb14.csv") %>% 
  mutate(Year = 2014) %>% 
  mutate(Team = case_when(
    Team == "Miami (FL) (ACC)" ~ "Miami_FL (ACC)",
    Team == "Miami (OH) (MAC)" ~ "Miami_OH (MAC)",
    TRUE ~ Team
  )) %>% separate(col = "Team", into = "Team", sep = " [(]")
cfb15 <- read_csv("Data/cfb15.csv") %>% 
  mutate(Year = 2015) %>% 
  mutate(Team = case_when(
    Team == "Miami (FL) (ACC)" ~ "Miami_FL (ACC)",
    Team == "Miami (OH) (MAC)" ~ "Miami_OH (MAC)",
    TRUE ~ Team
  )) %>% separate(col = "Team", into = "Team", sep = " [(]")
cfb16 <- read_csv("Data/cfb16.csv") %>% 
  mutate(Year = 2016) %>% 
  mutate(Team = case_when(
    Team == "Miami (FL) (ACC)" ~ "Miami_FL (ACC)",
    Team == "Miami (OH) (MAC)" ~ "Miami_OH (MAC)",
    TRUE ~ Team
  )) %>% separate(col = "Team", into = "Team", sep = " [(]")
cfb17 <- read_csv("Data/cfb17.csv") %>% 
  mutate(Year = 2017) %>% 
  mutate(Team = case_when(
    Team == "Miami (FL) (ACC)" ~ "Miami_FL (ACC)",
    Team == "Miami (OH) (MAC)" ~ "Miami_OH (MAC)",
    TRUE ~ Team
  )) %>% separate(col = "Team", into = "Team", sep = " [(]")
cfb18 <- read_csv("Data/cfb18.csv") %>% 
  mutate(Year = 2018) %>% 
  mutate(Team = case_when(
    Team == "Miami (FL) (ACC)" ~ "Miami_FL (ACC)",
    Team == "Miami (OH) (MAC)" ~ "Miami_OH (MAC)",
    TRUE ~ Team
  )) %>% separate(col = "Team", into = "Team", sep = " [(]")
cfb19 <- read_csv("Data/cfb19.csv") %>% 
  mutate(Year = 2019) %>% 
  mutate(Team = case_when(
    Team == "Miami (FL) (ACC)" ~ "Miami_FL (ACC)",
    Team == "Miami (OH) (MAC)" ~ "Miami_OH (MAC)",
    TRUE ~ Team
  )) %>% separate(col = "Team", into = "Team", sep = " [(]")
cfb20 <- read_csv("Data/cfb20.csv") %>% 
  mutate(Year = 2020) %>% 
  mutate(Team = case_when(
    Team == "Miami (FL) (ACC)" ~ "Miami_FL (ACC)",
    Team == "Miami (OH) (MAC)" ~ "Miami_OH (MAC)",
    TRUE ~ Team
  )) %>% separate(col = "Team", into = "Team", sep = " [(]")
cfb21 <- read_csv("Data/cfb21.csv") %>% 
  mutate(Year = 2021) %>% 
  select(-"...1") %>% 
  separate(col = "Team", into = "Team", sep = " [(]") 
```

``` {r edit data} 
names(cfb21) <- make.names(names(cfb21), unique=TRUE)
cfb_data <- bind_rows(cfb13, cfb14, cfb15, cfb16, cfb17, cfb18, cfb19, cfb20, cfb21)
coach_data <- bind_rows(coach13, coach14, coach15, coach16, coach17, coach18, coach19, coach20, coach21)
head(coach_data)
names(coach_data)[3] <- "Team"
cfb_data <- cfb_data %>% select(-c("...41", "Kickoff.Return.Def.Rank", "Opp.Kickoff.Returns", "Kickoff.Touchbacks", "Opponent.Kickoff.Return.Yards", "Opp.Kickoff.Return.Touchdowns.Allowed", "Avg.Yards.per.Kickoff.Return.Allowed", "Win.Loss", "NA.", "Interceptions.Thrown.y"))
#cfb_data$Conference <-gsub(")","",as.character(cfb_data$Conference))
#cfb_data[(cfb_data$Team == "Miami") & (cfb_data$Conference == "OH "), "Team"] <- "Miami (OH)" #need to figure out miami
coach_data <- coach_data %>% 
  filter(W + L > 7)
cfb_data[cfb_data == "App State"] <- "Appalachian State"
cfb_data[cfb_data == "Appalachian St."] <- "Appalachian State"
cfb_data[cfb_data == "Arizona St."] <- "Arizona State"
cfb_data[cfb_data == "Arkansas St."] <- "Arkansas State"
cfb_data[cfb_data == "Army West Point"] <- "Army"
cfb_data[cfb_data == "Ball St."] <- "Ball State"
cfb_data[cfb_data == "Boise St."] <- "Ball State"
cfb_data[cfb_data == "Central Mich."] <- "Central Michigan"
cfb_data[cfb_data == "Coastal Caro."] <- "Coastal Carolina"
cfb_data[cfb_data == "Colorado St."] <- "Colorado State"
cfb_data[cfb_data == "UConn"] <- "Connecticut"
cfb_data[cfb_data == "Eastern Mich."] <- "Eastern Michigan"
cfb_data[cfb_data == "Fla. Atlantic"] <- "Florida Atlantic"
cfb_data[cfb_data == "FIU"] <- "Florida International"
cfb_data[cfb_data == "Florida St."] <- "Florida State"
cfb_data[cfb_data == "Fresno St."] <- "Fresno State"
cfb_data[cfb_data == "Ga. Southern"] <- "Georgia Southern"
cfb_data[cfb_data == "Georgia St."] <- "Georgia State"
cfb_data[cfb_data == "Iowa St."] <- "Iowa State"
cfb_data[cfb_data == "Kansas St."] <- "Kansas State"
cfb_data[cfb_data == "Kent St."] <- "Kent State"
cfb_data[cfb_data == "La.-Monroe"] <- "Louisiana-Monroe"
cfb_data[cfb_data == "ULM"] <- "Louisiana-Monroe"
cfb_data[cfb_data == "Michigan St."] <- "Michigan State"
cfb_data[cfb_data == "Middle Tenn."] <- "Middle Tennessee State"
cfb_data[cfb_data == "Mississippi St."] <- "Mississippi State"
cfb_data[cfb_data == "New Mexico St."] <- "New Mexico State"
cfb_data[cfb_data == "NIU"] <- "Norhtern Illinois"
cfb_data[cfb_data == "Northern Ill."] <- "Norhtern Illinois"
cfb_data[cfb_data == "Ohio St."] <- "Ohio State"
cfb_data[cfb_data == "Oklahoma St."] <- "Oklahoma State"
cfb_data[cfb_data == "Oregon St."] <- "Oregon State"
cfb_data[cfb_data == "Penn St."] <- "Penn State"
cfb_data[cfb_data == "San Diego St."] <- "San Diego State"
cfb_data[cfb_data == "San Jose St."] <- "San Jose State"
cfb_data[cfb_data == "South Fla."] <- "South Florida"
cfb_data[cfb_data == "Southern Miss."] <- "Southern Mississippi"
cfb_data[cfb_data == "Southern California"] <- "USC"
cfb_data[cfb_data == "Western Mich."] <- "Western Michigan"
cfb_data[cfb_data == "Western Ky."] <- "Western Kentucky"
cfb_data[cfb_data == "Washington St."] <- "Washington State"
cfb_data[cfb_data == "Utah St."] <- "Utah State"
cfb_data[cfb_data == "Texas St."] <- "Texas State"
coach_data[coach_data == "Bowling Green State"] <- "Bowling Green"
coach_data[coach_data == "Brigham Young"] <- "BYU"
coach_data[coach_data == "North Carolina State"] <- "NC State"
coach_data[coach_data == "Pitt"] <- "Pittsburgh"
coach_data[coach_data == "Miami (FL)"] <- "Miami_FL"
coach_data[coach_data == "Miami (OH)"] <- "Miami_OH"
big_data <- inner_join(cfb_data, coach_data, by = c("Team", "Year")) %>% 
  select(c(Team, Coach, W, L, Pct, Year, Conf, Total.Points, Points.Allowed, Off.Rank, Off.Yards.Play, Turnover.Margin, Def.Rank, Touchdowns, Penalties, Penalty.Yards.Per.Game, Yards.Play.Allowed, Off.TDs.Allowed, Scoring.Off.Rank, Avg.Points.per.Game.Allowed, Touchdowns.Allowed))
```

```{r data analysis}
new_coach = c()
big_data <- big_data %>% 
  arrange(Team, Year)
loop_data <- big_data %>% 
    group_by(Team) 
for (i in 2:nrow(big_data)){
  if ((big_data$Team[i] == big_data$Team[i-1]) & (big_data$Coach[i] !=
                                                  big_data$Coach[i-1])){
    new_coach = append(new_coach, 1)
  }
  else{
    new_coach = append(new_coach, 0)
  }
}

big_data <- big_data[-1, ] %>% 
  cbind(new_coach)
big_data <- big_data %>% 
  mutate(new_coach = as.factor(new_coach))

old_data <- big_data %>% select(c("Turnover.Margin", "Touchdowns", "Scoring.Off.Rank"))
new_data <- paste("lag", old_data, sep = ".")

big_data <-
  big_data %>% 
  group_by(Team) %>% 
  mutate(lastyr_TD = lag(Touchdowns, n = 1, default = NA),
         lastyr_TOmargin = lag(Turnover.Margin, n = 1, default = NA),
         lastyr_pct = lag(Pct, n = 1, default = NA),
         lastyr_TD.allowed = lag(Off.TDs.Allowed, n = 1, default = NA),
         delta_TD = Touchdowns - lastyr_TD,
         delta_pct = Pct - lastyr_pct,
         delta_TD.allowed = Off.TDs.Allowed - lastyr_TD.allowed) %>% 
  filter(Conf %in% c("ACC", "Big Ten", "Big 12", "Pac-12", "SEC")) %>% 
  filter(Year != 2013)
  
  
lm.1 <- lm(delta_pct ~ new_coach, data = big_data)
summary(lm.1)
```









